
project:
  type: website
  output-dir: docs

website:
  title: "FinTech"
  navbar:
    search: true
    collapse: false
    left:
      - text: "Research"
        file: papers.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

